//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeslaComClient.TeslaCommunication {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HardwareState", Namespace="http://schemas.datacontract.org/2004/07/TeslaCommunication")]
    [System.SerializableAttribute()]
    public partial class HardwareState : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool enabledF1Field;
        
        private bool enabledF2Field;
        
        private bool enabledF3Field;
        
        private bool enabledF4Field;
        
        private bool ledLightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool enabledF1 {
            get {
                return this.enabledF1Field;
            }
            set {
                if ((this.enabledF1Field.Equals(value) != true)) {
                    this.enabledF1Field = value;
                    this.RaisePropertyChanged("enabledF1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool enabledF2 {
            get {
                return this.enabledF2Field;
            }
            set {
                if ((this.enabledF2Field.Equals(value) != true)) {
                    this.enabledF2Field = value;
                    this.RaisePropertyChanged("enabledF2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool enabledF3 {
            get {
                return this.enabledF3Field;
            }
            set {
                if ((this.enabledF3Field.Equals(value) != true)) {
                    this.enabledF3Field = value;
                    this.RaisePropertyChanged("enabledF3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool enabledF4 {
            get {
                return this.enabledF4Field;
            }
            set {
                if ((this.enabledF4Field.Equals(value) != true)) {
                    this.enabledF4Field = value;
                    this.RaisePropertyChanged("enabledF4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ledLight {
            get {
                return this.ledLightField;
            }
            set {
                if ((this.ledLightField.Equals(value) != true)) {
                    this.ledLightField = value;
                    this.RaisePropertyChanged("ledLight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://STM32TeslaCommunication", ConfigurationName="TeslaCommunication.ICommunicationProtocol")]
    public interface ICommunicationProtocol {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://STM32TeslaCommunication/ICommunicationProtocol/Connect", ReplyAction="http://STM32TeslaCommunication/ICommunicationProtocol/ConnectResponse")]
        bool Connect(string comPortName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://STM32TeslaCommunication/ICommunicationProtocol/Connect", ReplyAction="http://STM32TeslaCommunication/ICommunicationProtocol/ConnectResponse")]
        System.Threading.Tasks.Task<bool> ConnectAsync(string comPortName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://STM32TeslaCommunication/ICommunicationProtocol/IsConnected", ReplyAction="http://STM32TeslaCommunication/ICommunicationProtocol/IsConnectedResponse")]
        bool IsConnected();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://STM32TeslaCommunication/ICommunicationProtocol/IsConnected", ReplyAction="http://STM32TeslaCommunication/ICommunicationProtocol/IsConnectedResponse")]
        System.Threading.Tasks.Task<bool> IsConnectedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://STM32TeslaCommunication/ICommunicationProtocol/Disconnect", ReplyAction="http://STM32TeslaCommunication/ICommunicationProtocol/DisconnectResponse")]
        void Disconnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://STM32TeslaCommunication/ICommunicationProtocol/Disconnect", ReplyAction="http://STM32TeslaCommunication/ICommunicationProtocol/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://STM32TeslaCommunication/ICommunicationProtocol/ClearQueues", ReplyAction="http://STM32TeslaCommunication/ICommunicationProtocol/ClearQueuesResponse")]
        void ClearQueues();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://STM32TeslaCommunication/ICommunicationProtocol/ClearQueues", ReplyAction="http://STM32TeslaCommunication/ICommunicationProtocol/ClearQueuesResponse")]
        System.Threading.Tasks.Task ClearQueuesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://STM32TeslaCommunication/ICommunicationProtocol/setEnabled", ReplyAction="http://STM32TeslaCommunication/ICommunicationProtocol/setEnabledResponse")]
        void setEnabled(byte num, bool enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://STM32TeslaCommunication/ICommunicationProtocol/setEnabled", ReplyAction="http://STM32TeslaCommunication/ICommunicationProtocol/setEnabledResponse")]
        System.Threading.Tasks.Task setEnabledAsync(byte num, bool enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://STM32TeslaCommunication/ICommunicationProtocol/getHardwareState", ReplyAction="http://STM32TeslaCommunication/ICommunicationProtocol/getHardwareStateResponse")]
        TeslaComClient.TeslaCommunication.HardwareState getHardwareState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://STM32TeslaCommunication/ICommunicationProtocol/getHardwareState", ReplyAction="http://STM32TeslaCommunication/ICommunicationProtocol/getHardwareStateResponse")]
        System.Threading.Tasks.Task<TeslaComClient.TeslaCommunication.HardwareState> getHardwareStateAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommunicationProtocolChannel : TeslaComClient.TeslaCommunication.ICommunicationProtocol, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommunicationProtocolClient : System.ServiceModel.ClientBase<TeslaComClient.TeslaCommunication.ICommunicationProtocol>, TeslaComClient.TeslaCommunication.ICommunicationProtocol {
        
        public CommunicationProtocolClient() {
        }
        
        public CommunicationProtocolClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommunicationProtocolClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommunicationProtocolClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommunicationProtocolClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Connect(string comPortName) {
            return base.Channel.Connect(comPortName);
        }
        
        public System.Threading.Tasks.Task<bool> ConnectAsync(string comPortName) {
            return base.Channel.ConnectAsync(comPortName);
        }
        
        public bool IsConnected() {
            return base.Channel.IsConnected();
        }
        
        public System.Threading.Tasks.Task<bool> IsConnectedAsync() {
            return base.Channel.IsConnectedAsync();
        }
        
        public void Disconnect() {
            base.Channel.Disconnect();
        }
        
        public System.Threading.Tasks.Task DisconnectAsync() {
            return base.Channel.DisconnectAsync();
        }
        
        public void ClearQueues() {
            base.Channel.ClearQueues();
        }
        
        public System.Threading.Tasks.Task ClearQueuesAsync() {
            return base.Channel.ClearQueuesAsync();
        }
        
        public void setEnabled(byte num, bool enabled) {
            base.Channel.setEnabled(num, enabled);
        }
        
        public System.Threading.Tasks.Task setEnabledAsync(byte num, bool enabled) {
            return base.Channel.setEnabledAsync(num, enabled);
        }
        
        public TeslaComClient.TeslaCommunication.HardwareState getHardwareState() {
            return base.Channel.getHardwareState();
        }
        
        public System.Threading.Tasks.Task<TeslaComClient.TeslaCommunication.HardwareState> getHardwareStateAsync() {
            return base.Channel.getHardwareStateAsync();
        }
    }
}
